name: CI for Java Invoice
on: [push]
jobs:
  test:
    name: Unit test

    strategy:
      matrix:
        java: [ 8, 13, 15 ]

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Maven tests
        run: mvn test
  lint:
    name: Check code with checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Checkstyle
        run: mvn checkstyle:check

